name: Build and Push Frontend Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node, Install dependencies and Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Додаємо два теги: latest та за commit SHA
          tags: |
            ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
            ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}
